[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/"
    [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(); microphone=(); camera=()"

  [[headers.values]]
  Cache-Control = "public, max-age=0, must-revalidate"

  [[headers.values]]
  Content-Encoding = "gzip"

  [[headers.values]]
  ETag = ""

  [[headers.values]]
  Content-Type = "text/html; charset=UTF-8"

  [[headers.values]]
  strict-transport-security = "max-age=31536000; includeSubDomains; preload"
  
  [[headers.values]]
  feature-policy = "geolocation 'self'; microphone 'self'; camera 'self'"

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, s-maxage=86400"
    Link = "</_next/static/style.css>; rel=preload; as=style,</_next/static/script.js>; rel=preload; as=script"

[[headers]]
  for = "/_next/static/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
