[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Feature-Policy = "camera 'none'; display-capture 'none'; document-domain 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Content-Security-Policy = "default-src https://healthymuscles.co.uk; script-src https://healthymuscles.co.uk https://www.google.com/maps; style-src https://healthymuscles.co.uk; img-src https://healthymuscles.co.uk data: https://www.google.com/maps; connect-src https://healthymuscles.co.uk https://www.google.com/maps; font-src https://healthymuscles.co.uk data: https://www.google.com/maps; object-src https://healthymuscles.co.uk; media-src https://healthymuscles.co.uk; frame-src https://healthymuscles.co.uk https://maps.google.com https://www.google.com/maps;"
