import "./globals.css";
import "@fontsource/work-sans";
import "@fontsource/prata"
import "@fontsource/dm-sans"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
