import "./globals.css";
import "@fontsource/work-sans";
import "@fontsource/prata";
import "@fontsource/dm-sans";
import Navigation from "@/components/navigation/Navigation";
import Banner from "@/components/banner/Banner";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Banner />
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
