import "./globals.css";
import "@fontsource/work-sans";
import "@fontsource/prata";
import "@fontsource/dm-sans";
import Navigation from "@/components/navigation/Navigation";
import Footer from "@/components/footer/Footer";
import MobileNavigation from "@/components/navigation/MobileNavigation";
import { draftMode } from "next/headers";
import ExitDraftModeLink from "./ExitDraftModeLink";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <MobileNavigation />
        {draftMode().isEnabled && (
          <p className="bg-orange-200 py-4 px-[6vw]">
            Draft mode is on! <ExitDraftModeLink className="underline" />
          </p>
        )}
        {children}
        {/* @ts-expect-error Server Component */}
        <Footer />
      </body>
    </html>
  );
}
